### ISSUE TITLE
[HELP] how do I get it working corecrly

### ISSUE THREAD

**Issue by MartijnW29** [thearyadev/MSRF#36]
**Describe the bug**

**Expected behavior**

**Version Number**
The exact version you are experiencing this error in.

**Error Report**
Go into the directory of the `msrf.exe` application and look for a folder called `errors`.  This folder will include auto generated error reports to help debug problems. 

These error reports may include personal information, so please read the following:

Error reports will show up in the log window, it will say "Error report generated" with a filename at the end. That is the zipfile that includes the error report for that specific error. 

- Error Information
	- Account data (Same account data used for earning points, this information does not contain any account credentials, only account information like: point count, available promotions, etc.) 
	- Browser screenshot at the time of the error. This may include the account name, and potentially the account email. If you plan on sharing this (such as in a Github issue), you may want to cover any personal information
	- A traceback. This is the exception raised by python. 
	- The HTML page at the time of the error. This helps in determining exactly why an error happened, but this file will have personal information, such as your email address and name. You may not want to include this when sharing this with other people. If you are familiar with HTML structure, you can find and remove that personal information before sharing. 
	- the url that the exception occured on.

You can unzip the error report and hide any personal information before including it in your Github issue. 

Including an error report in your issue will help me solve your problem. Many issues in MSRF are directly related to the microsoft account and changes/variations in Microsoft rewards. The error report targets exactly what the problem is. You are unlikely to get help by creating an issue that says "Its not working" with no additional information.

I get this error when i try to run the program i did install poetry

C:\Users\Marti\Desktop\MSRF-main>python main.py
Traceback (most recent call last):
  File "C:\Users\Marti\Desktop\MSRF-main\main.py", line 15, in <module>
    import database
  File "C:\Users\Marti\Desktop\MSRF-main\database\__init__.py", line 1, in <module>
    from .database_access import *
  File "C:\Users\Marti\Desktop\MSRF-main\database\database_access.py", line 3, in <module>
    import util
  File "C:\Users\Marti\Desktop\MSRF-main\util\__init__.py", line 1, in <module>
    from .configloader.config import *
  File "C:\Users\Marti\Desktop\MSRF-main\util\configloader\config.py", line 2, in <module>
    from pydantic_yaml import YamlModel
ImportError: cannot import name 'YamlModel' from 'pydantic_yaml' (C:\Users\Marti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_yaml\__init__.py)

**Comment by MartijnW29** [comment]
what i did was install the zip, unzip it, run install poetry and then i ran main.py

**Comment by MartijnW29** [comment]
dixed it i installed the wrong thing i had to go to releases and download windows 64 bit version
